{% set version = "3.0" %}

package:
  name: tzlocal
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tzlocal/tzlocal-{{ version }}.tar.gz
  sha256: f4e6e36db50499e0d92f79b67361041f048e2609d166e93456b50746dc4aef12

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - backports.zoneinfo

test:
  imports:
    - tzlocal

about:
  home: https://github.com/regebro/tzlocal
  license: MIT
  license_file: LICENSE.txt
  summary: tzinfo object for the local timezone
  dev_url: https://github.com/regebro/tzlocal

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
    - synapticarbors
