{% set version = "5.0.1" %}

package:
  name: tzlocal
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tzlocal/tzlocal-{{ version }}.tar.gz
  sha256: 46eb99ad4bdb71f3f72b7d24f4267753e240944ecfc16f25d2719ba89827a803

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<36]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - backports.zoneinfo  # [py<39]
    - python-tzdata  # [win]
    - pytz-deprecation-shim

test:
  requires:
    - pip
  imports:
    - tzlocal
  commands:
    - pip check

about:
  home: https://github.com/regebro/tzlocal
  license: MIT
  license_file: LICENSE.txt
  summary: tzinfo object for the local timezone
  dev_url: https://github.com/regebro/tzlocal

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
    - synapticarbors
