{% set version = "5.3.1" %}

package:
  name: tzlocal
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/tzlocal/tzlocal-{{ version }}.tar.gz
  sha256: cceffc7edecefea1f595541dbd6e990cb1ea3d19bf01b2809f362a03dd7921fd

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools >=64
  run:
    - python
    - python-tzdata  # [win]

test:
  requires:
    - pip
  imports:
    - tzlocal
  commands:
    - pip check

about:
  home: https://github.com/regebro/tzlocal
  license: MIT
  license_file: LICENSE.txt
  summary: tzinfo object for the local timezone
  dev_url: https://github.com/regebro/tzlocal

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
    - synapticarbors
