schema_version: 1

context:
  version: "5.4"

package:
  name: tzlocal
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/tzlocal/tzlocal-${{ version }}.tar.gz
  sha256: 41e1293f80d4b5ff38dff222601a8fbd06b4fdcaf25e224704047ad26a39af54

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-build-isolation --no-deps

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=64
  run:
    - python >=${{ python_min }}
    - if: win
      then:
        - python-tzdata
        - __win
      else:
        - __unix

tests:
  - python:
      imports:
        - tzlocal
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE.txt
  summary: tzinfo object for the local timezone
  homepage: https://github.com/regebro/tzlocal
  repository: https://github.com/regebro/tzlocal

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
    - synapticarbors
